services:
  - type: web
    name: calendrify-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 5037
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://calendrify-backend.onrender.com/api/auth/google/callback
      - key: FRONTEND_URL
        value: https://calendrify-delta.vercel.app
